# .pre-commit-config.yaml
# Dbt Demo: Jaffle Shop
#
# Copyright © 2023 djrlj694.dev. All rights reserved.
#
# The pre-commit (multi-language package manager configuration file for Git
# pre-commit hook scripts -- i.e., hooks) configuration file. Specifies which
# pre-commit plugins (each by Git repository and hook set) are installed and
# set for identifying simple issues (missing semicolons, trailing whitespace,
# debug statements, etc.) before submission to code review. Allows code
# reviewers to focus on the architecture of a change while not wasting time
# with trivial style nitpicks.
#
# REFERENCES:
# 1. https://docs.getdbt.com/blog/enforcing-rules-pre-commit-dbt
# 2. https://github.com/dbt-labs/jaffle-shop-template/blob/main/.pre-commit-config.yaml
# 3. https://blog.montrealanalytics.com/automating-dbt-development-workflows-with-pre-commit-b6c7ca708f7
# 4. https://pre-commit.com/hooks.html
# 5. https://pre-commit.com/index.html#plugins


# All commands by default will run on every commit
# default_install_hook_types:
# - pre-commit
default_stages:
  - commit
  - push

# Some configs are only available after v2.16
minimum_pre_commit_version: '2.16'

# Check for issues or automatically fix issues.
repos:

  ### Pre-commit ###

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  ### Git ###

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.2.2
    hooks:
      - id: commitizen
        stages: [commit-msg]
      - id: commitizen-branch
        stages:
          - post-commit
          - post-rewrite
          - push

  ### Git, Polyglot ###

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      # - id: check-ast
      # - id: check-builtin-literals
      - id: check-byte-order-marker
      # - id: check-docstring-first
      # - id: check-executables-have-shebangs
      # - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      # - id: check-symlinks
      # - id: check-toml
      - id: check-vcs-permalinks
      # - id: check-xml
      - id: check-yaml
      # - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-aws-credentials
      - id: detect-private-key
      # - id: double-quote-string-fixer
      - id: end-of-file-fixer
      # - id: file-contents-sorter
      - id: fix-byte-order-marker
      # - id: fix-encoding-pragma
      #   args: [--remove]
      # - id: forbid-new-submodules
      - id: mixed-line-ending
      # - id: name-tests-test
      - id: no-commit-to-branch
      # - id: pretty-format-json
      #   args: [--autofix, --no-sort-keys]
      # - id: requirements-txt-fixer
      # - id: sort-simple-yaml
      - id: trailing-whitespace

  ### Dbt ###

  # - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
  #   rev: v1.1.0
  #   hooks:
  #     - id: dbt-docs-generate
  #     - id: check-model-has-properties-file
  #       name: Check that all models are listed in a YAML file
  #       files: ^models/
  #     - id: check-model-has-tests
  #       name: Check that all models have tests
  #       files: ^models/

  ### Markdown ###

  - repo: https://github.com/frnmst/md-toc
    rev: 8.1.9
    hooks:
      - id: md-toc

  ### Python ###

  # - repo: https://github.com/asottile/add-trailing-comma
  #   rev: v2.4.0
  #   hooks:
  #     - id: add-trailing-comma
  #       args: [--py36-plus]

  ### SQL ###

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.0.3
    hooks:
      - id: sqlfluff-lint
        # For dbt projects, this installs the dbt "extras".
        # You will need to select the relevant dbt adapter for your dialect
        # (https://docs.getdbt.com/docs/available-adapters):
        additional_dependencies: ['dbt-postgres', 'sqlfluff-templater-dbt']
      - id: sqlfluff-fix
        # Arbitrary arguments to show an example
        # args: [--rules, "L003,L014"]
        additional_dependencies: ['dbt-postgres', 'sqlfluff-templater-dbt']
