# dbt_project.yml
# Dbt Demo: COVID-19
#
# Copyright © 2023 djrlj694.dev. All rights reserved.
#
# The dbt project configuration file. Identifies its parent directory as the
# root of a dbt project. Specifies how dbt operates on said project.
#
# REFERENCES:
# 1. https://docs.getdbt.com/guides/best-practices/how-we-structure/5-the-rest-of-the-project
# 2. https://docs.getdbt.com/docs/build/projects
# 4. https://docs.getdbt.com/blog/how-to-design-and-structure-metrics
# 5. https://docs.getdbt.com/reference/dbt_project.yml
# 5. https://github.com/dbt-labs/dbt-databricks-demo
# 6. https://github.com/dbt-labs/jaffle_shop
# 7. https://github.com/dbt-labs/jaffle_shop_metrics
# 8. https://github.com/dbt-labs/jaffle-shop-template


# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: dbt_demo_jaffle
version: v0.3.1
config-version: 2
require-dbt-version: [">=1.2.0-rc1", "<2.0.0"]

# This setting configures which "profile" dbt uses for this project.
profile: dbt_demo_jaffle

# These configurations specify where dbt should look for different types of
# files. For example, the `model-paths` config states that models in this
# project can be found in the "models/" directory. You probably won't need to
# change these!
model-paths: [models]
analysis-paths: [analyses]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

target-path: target                  # Directory to store compiled SQL files
packages-install-path: dbt_packages

clean-targets:                       # Directories to be removed by `dbt clean`
  - target
  - dbt_packages
  - logs

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dbt_demo_jaffle:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      finance:
        +schema: finance
      marketing:
        +schema: marketing
    metrics:
      - _metrics.yml
